language: go

go:
  - 1.9.x
  - 1.10.x

go_import_path: github.com/lintanghui/discovery

install:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - gometalinter --vendor --disable-all --enable=gosimple --enable=golint --enable=vet --enable=ineffassign --enable=unconvert \
    --exclude="by other packages, and that stutters; consider calling this" \
    --skip=proto \
    --skip=vendor \
    --skip=.git \
    --tests ./...
  - go test ./registry/...
  - go test ./discovery/...
  - cd cmd/discovery
  - go build

after_success:
  - bash <(curl -s https://codecov.io/bash)
